version: '3'

volumes:
  nextcloud-data:
  nextcloud-db:

networks:
  backend:
services:
  nextcloud-app:
    image: nextcloud
    restart: always
    ports:
    - "80:80"
    - "4443:4443"
    volumes:
      - /srv/usb8tbmnt/nextcloud/data/data:/var/www/html/data
      - /srv/usb8tbmnt/nextcloud/data/config:/var/www/html/config
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - PHP_UPLOAD_LIMIT=10G
      - PHP_MEMORY_LIMIT=512M
    networks:
      - backend

  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - /srv/usb8tbmnt/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend
